# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $replyTo: 'nasira3795@gmail.com'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Repository/Traits/'

    App\Service\MailerService:
        arguments:
            $replyTo: 'nasira3795@gmail.com'
            $logger: '@logger'

    App\EventListener\PersonneListener:
        tags:
            - { name: kernel.event_listener, event: personne.add }
